Add retry
sopel-irc/sopel-youtube pull request #11
Opened 2018-01-24 01:38 UTC by freeboson

Because we can only use an older version of Google's python API bindings, you do not get retries builtin. This makes YT lookups unreliable. This PR catches `ConnectionError`, sleeps with an exponential backoff and tries again.

2018-05-08 18:26 UTC, dgw requested changes
Looks good, just a couple nitpicky style tweaks.

Would also be much appreciated if the commit message was made longer than one word. The PR title and OP would make a pretty great commit message, actually. :smile_cat:

2018-05-08 18:26 UTC, dgw commented on sopel_modules/youtube/youtube.py
> +num_retries = 5
Two blank lines after, one before, please. (Really, it's two blank lines before the class definition, but this is the line you changed. :grin:

2018-05-08 18:26 UTC, dgw commented on sopel_modules/youtube/youtube.py
> +        try :
No space between `try` and `:`

2018-05-08 18:26 UTC, dgw commented on sopel_modules/youtube/youtube.py
> +        try :
No space between `try` and `:`

2018-05-09 01:54 UTC, freeboson commented
This is an old PR. I've made quite a few changes. I don't think the retry even works as it is. I'll just push up my current version and you can review that if you're still interested.

2018-05-09 02:05 UTC, dgw commented
There are open PRs in this repo from 2014, this isn't old lol.

I can touch this one up myself if you make sure that "Allow edits from maintainers" box is checked.

2018-05-09 02:09 UTC, freeboson commented
Haha, to be clear I meant "old" like out-of-sync with what I have atm.

2018-05-09 02:13 UTC, dgw commented
By that definition of "old", a PR opened two seconds ago could be "old"!

2018-05-09 02:20 UTC, dgw approved these changes
Addressed my own style comments via the magic of GitHub allowing edits from maintainers on PR branches.

2018-05-10 01:21 UTC, freeboson commented
If you do it this way, you'll get `NameError`. I think it's better to have a message if failures > 5.

2018-05-10 02:06 UTC, dgw commented
Wasn't sure exactly what you meant (line notes are clearer) but how does ab2b102 look?

2019-05-25 21:32 UTC, dgw commented
If this breaks anything, we'll just have to make another release. :joy:

2019-05-25 21:32 UTC, merged